### ISSUE TITLE
PreArm: Motor Interlock Enabled for multicopters in SITL

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1996]
When SITL for multicopters is selected, the pre-arm message, "PreArm: Motor Interlock Enabled" appears.  I'm very unsure of the caused..

**Comment by meee1** [comment]
this was an issue with the server I use to build the sitl binary's. it if fixed now

**Comment by prem48science** [comment]
@meee1 I am still facing the error in Heli SITL. I downloaded binary directly from the mission planner from the simulation tab.
