### ISSUE TITLE
NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  

### ISSUE THREAD

**Issue by gitfishup** [ArduPilot/MissionPlanner#2668]
#### Issue details
I use the latest source code.

Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	wasm	C:\Program Files\dotnet\sdk\5.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	

![image](https://user-images.githubusercontent.com/69180601/128305301-53aab24b-1106-4d87-8a9a-68389c373cec.png)

Target framework:
![image](https://user-images.githubusercontent.com/69180601/128305375-17306a70-136d-41a7-9876-4482117193f3.png)

vs2019 version 
![image](https://user-images.githubusercontent.com/69180601/128305206-e0a90f53-bc1c-46aa-a3fb-bf9c4f6e3acf.png)

What 's going on?

**Comment by gitfishup** [comment]
go to https://dotnet.microsoft.com/download/dotnet/6.0 to download a dotnet-sdk-6 for vs2019 16.10 , install it ,then the problem is solved.

![image](https://user-images.githubusercontent.com/69180601/128446034-221cf49a-69f0-4997-b5cd-070bac210842.png)

**Comment by MLEI-AERO** [comment]
I still have the same problem. Installing .NET 6.0.0-preview for my VS2019 16.11.0 doesn't solve it. Do I have to set a path or anything in VS?

![grafik](https://user-images.githubusercontent.com/61831930/130616897-34c1c3fe-59dc-41cb-b829-465e32502380.png)

**Comment by gitfishup** [comment]
> I still have the same problem. Installing .NET 6.0.0-preview for my VS2019 16.11.0 doesn't solve it. Do I have to set a path or anything in VS?
> 
> ![grafik](https://user-images.githubusercontent.com/61831930/130616897-34c1c3fe-59dc-41cb-b829-465e32502380.png)
@MLEI-AERO I solved the problem at the beginning.But the problem came up again the next day.If vscode prompts you to update something, restart after the update.If you haven't updated anything, try building a new missionplanner.After installing NET, if the problem still occurs, this is how I solve it

**Comment by danilopmaciel** [comment]
Same problem 
![image](https://user-images.githubusercontent.com/30030866/181343421-0e86d6f0-3cdb-4c59-8291-dbc8f68c4104.png)

**Comment by meee1** [comment]
install dotnet 6
